// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exyvqkspisjcdixcobcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eXZxa3NwaXNqY2RpeGNvYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzUzODMsImV4cCI6MjA2ODE1MTM4M30.LbVChk1PRGaQbbueIZB75c0lupSfCufJZ-mzreBHJWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});